config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'orders/buses-bulk-update/:id' => 'orders#bulk_update', :as => 'bulk_update'
  post 'orders/buses-bulk-update-save/:id' => 'orders#bulk_update_save', :as => 'bulk_update_save'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ferries, only: [:index, :show, :edit, :update, :destroy]
  resources :buses do
    collection do
      get 'vn'
      get 'vo'
    end
    collection do
      get 'archive'
    end
    resources :ferries, only: [:create]
  end
  resources :orders do
    collection do
      get 'closed'
      get 'archive'
    end
    resources :buses do
      resources :lines, only: [:new, :create] do
        resources :trades, only: [:new, :create]
        resources :buses, only: [:new, :create]
        resources :trainings, only: [:new, :create]
      end
    end
  end

  resources :factory_orders, only: [:show, :edit, :update] do
    resources :partners
  end
  resources :documents, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :deliveries, only: [:index, :show, :edit, :update] do
    member do
      get 'close'
    end
    collection do
      get 'archive'
    end
  end
  resources :lines, only: [:edit, :update, :destroy]
  resources :works, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :trades, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'archive'
    end
    member do
      get 'close'
    end
  end
  resources :trainings, only: [:destroy]

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
  has_many :lines, dependent: :destroy
  accepts_nested_attributes_for :lines
  has_many :factory_orders, dependent: :destroy
  accepts_nested_attributes_for :factory_orders
  belongs_to :description, optional: true
  belongs_to :type, optional: true
  has_many :orders, through: :lines
  has_many :ferries, dependent: :destroy
  accepts_nested_attributes_for :ferries
  has_many :trades, dependent: :destroy
  has_many :partners, through: :factory_orders
  accepts_nested_attributes_for :partners

  enum statut1: { disponible: 0, indisponible: 1, facture_livre: 2, en_commande: 3 }

  scope :ordered, -> { includes(:lines, :orders).where(orders: {statut: "pending"} ) }
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :place, optional: true
  has_one :line, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :works
  accepts_nested_attributes_for :works,  reject_if: :all_blank, allow_destroy: true
  has_one :order, through: :line
  has_one_attached :attestation_amenagement
  has_one_attached :coc
  has_one_attached :cpi
  has_one_attached :cerfa_changement_titulaire
  has_one_attached :cerfa_cession
  has_one_attached :bulletion_de_livraison
  has_one_attached :cdoc
  has_one_attached :attestation_ead
  has_one_attached :attestation_limiteur_de_vitesse
  has_one_attached :photos_vehicule
  has_one_attached :facture
  has_one_attached :bon_de_commande
  has_one_attached :offre_configuration_avec_plan_implantation
  has_one_attached :information_peinture
  has_one_attached :plan_vosp
  has_one_attached :fiche_rcr
  has_one_attached :a_reception_envoi_papiers_originaux
  has_one_attached :justificatif_financement

  enum statut: { pending: 0, close: 1, cancel: 2 }
end

app/models/description.rb
class Description < ApplicationRecord
  has_many :buses
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :factory_order, optional: true
  belongs_to :delivery, optional: true
  belongs_to :trade, optional: true
  mount_uploader :pdf, PfdFileUploader
end

app/models/employee_partner.rb
class EmployeePartner < ApplicationRecord
  belongs_to :partner, optional: true
end

app/models/factory_order.rb
class FactoryOrder < ApplicationRecord
  belongs_to :bus, optional: true
  belongs_to :partner, optional: true
  has_many :documents, dependent: :destroy
  has_many :employee_partners, through: :partner
  has_one_attached :vcr
  has_one_attached :document_de_transport
  has_one_attached :delivery_note
  has_one_attached :vcr
  has_many_attached :photos_livraison

  enum statut: { pending: 0, close: 1, cancel: 2 }

end

app/models/ferry.rb
class Ferry < ApplicationRecord
  belongs_to :bus, optional: true
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :bus
  belongs_to :order_book, optional: true
  has_many :trades, dependent: :destroy
  has_one :training, dependent: :destroy
  belongs_to :delivery, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :sales_advisor
  validates :sales_advisor, presence: true
  has_many :lines, dependent: :delete_all
  has_many :buses, through: :lines
  has_many :trades, through: :lines, dependent: :destroy
  has_many :trainings, through: :lines, dependent: :destroy

  enum statut: { pending: 0, close: 1, archive: 2 }
end

app/models/order_book.rb
class OrderBook < ApplicationRecord
  has_many :lines
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :factory_orders
  has_many :employee_partners
  has_many :buses, through: :factory_orders
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :deliveries
end

app/models/sales_advisor.rb
class SalesAdvisor < ApplicationRecord
  has_many :orders
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :work, optional: true
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :line
  belongs_to :bus
  has_many :documents, dependent: :destroy
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :line
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :buses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :delivery, optional: true
  has_one_attached :devis
  has_one_attached :facture_travaux
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>

  </head>
  <body>
    <header>
  <%= render 'shared/navbar' %>
</header>

    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_documents.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"></div>
  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        <th><%= locals[:title] %></th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% object.each do |document| %>
      <tr>
        <td><%= document %> </td>
        <td>
         <% if locals[:model].documents.where(name: "#{document}").take.present?  %>
          <%= link_to document_path(locals[:model].documents.where(name: "#{document}").take, :name => "#{document}"), class:"btn btn-primary" do %><i class="far fa-eye"></i><% end %>
          <%= link_to edit_document_path(locals[:model].documents.where(name: "#{document}").take, :name => "#{document}"), class:"btn btn-warning" do %><i class="far fa-edit"></i><% end %>
          <%= link_to document_path(locals[:model].documents.where(name: "#{document}").take, :name => "#{document}"), method: :delete, class:"btn btn-danger" do %><i class="far fa-eye"></i><% end %>
          <% else %>
          <%=link_to new_document_path(:name => "#{document}"), class:"btn btn-primary" do %><i class="fas fa-plus-circle"></i><% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.volvobuses.fr/content/dam/volvo/volvo-buses/master/bre/home/140x140-Volvo-iron-mark.png/_jcr_content/renditions/140x140-Volvo-iron-mark-logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Commandes", orders_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Véhicule", vn_buses_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Convoyages", ferries_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Livraisons", deliveries_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Reprises", trades_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="nav-link" data-toggle="dropdown"><%= current_user.email %></div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>