config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'orders/buses-bulk-update/:id' => 'orders#bulk_update', :as => 'bulk_update'
  post 'orders/buses-bulk-update-save/:id' => 'orders#bulk_update_save', :as => 'bulk_update_save'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ferries, only: [:index, :show, :edit, :update, :destroy]
  resources :buses do
    collection do
      get 'vn'
      get 'vo'
    end
    collection do
      get 'archive'
    end
    resources :ferries, only: [:create]
  end
  resources :orders do
    collection do
      get 'closed'
      get 'archive'
    end
    resources :buses do
      resources :lines, only: [:new, :create] do
        resources :trades, only: [:new, :create]
        resources :buses, only: [:new, :create]
        resources :trainings, only: [:new, :create]
      end
    end
  end

  resources :factory_orders, only: [:show, :edit, :update] do
    resources :partners
  end
  resources :documents, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :deliveries, only: [:index, :show, :edit, :update] do
    member do
      get 'close'
    end
    collection do
      get 'archive'
    end
  end
  resources :lines, only: [:edit, :update, :destroy]
  resources :works, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :trades, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'archive'
    end
    member do
      get 'close'
    end
  end
  resources :trainings, only: [:destroy]

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :sales_advisor
  validates :sales_advisor, presence: true
  has_many :lines, dependent: :delete_all
  has_many :buses, through: :lines
  has_many :trades, through: :lines, dependent: :destroy
  has_many :trainings, through: :lines, dependent: :destroy

  enum statut: { pending: 0, close: 1, archive: 2 }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]


  def index
    @descriptions = Description.all
    @types = Type.all
    @orders = Order.pending
  end

  def new
    @order = Order.new
    @sales_advisors = SalesAdvisor.all
    @order_books = OrderBook.all
  end

  def create
    @order = Order.new(order_params)
    @order.pending!
    if @order.save
      redirect_to order_path(@order[:id])
    else
      render :new
    end
  end

  def show
    @ordered_buses = @order.buses
    session[:order_id] = @order.id
    @bus = Bus.new
    @descriptions = Description.all
    @types = Type.all
    @buses = []
    @q = Bus.ransack(params[:q])
    if params[:q].present?
      search_stock if params[:q][:type_name_cont].present?
    end
    @order_to_close = true if order_to_close?
  end

  def edit
  end

  def archive
    @descriptions = Description.all
    @types = Type.all
    @orders = Order.archive
  end

  def update
    @order.update(order_params)
    redirect_to order_path(@order[:id])
  end

  def bulk_update
    @order = Order.find(params[:id])
    @buses = @order.buses
  end

  def bulk_update_save
    @order = Order.find(params[:id])
    if params[:buses].present?
      result = Bus.update(params[:buses].keys, params[:buses].values).reject { |p| p.errors.empty? }
      @bus = Bus.find(params[:buses].keys.first)
      if result.empty?
        flash[:notice] = "Statut des véhicule mis à jour"
      else
        render :bulk_update
      end
    end
    erase_all_line
    erase_all_trade
    erase_all_training
    @order.archive!
    redirect_to orders_path
  end

  def closed
    @descriptions = Description.all
    @types = Type.all
    @orders = Order.close
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_to_close?
    answer = true
    answer = false unless @ordered_buses.present?
    @ordered_buses.each do |bus|
      answer = false if bus.facture_livre?
    end
    @order.lines.each do |line|
      line.trades.each do |trade|
        # le status d'un trade est passé a false quand la reprise est cloturée
        answer = false if trade.status == false
      end
    end
    return answer
  end

  def erase_all_trade
    @order.trades.each do |trade|
      #le bus repris est rendu au client
      trade.documents.each do |document|
        document.delete
      end
      bus = trade.bus
      bus.facture_livre!
      bus.statut2 = ""
      bus.save
      trade.delete
    end
  end

  def erase_all_training
    @order.trainings.each do |training|
      training.delete
    end
  end

  def set_bus_to_available
    @order.buses.each do |bus|
      bus.disponible!
      bus.save
    end
  end

  def erase_all_line
    @order.lines.each do |line|
      delivery = line.delivery
      # efface le bus si commandé uniquement pour cette commande
      #bus_to_cancel = line.bus if line.bus.statut2 == "A commander"
      # delivery.documents.each do |document|
      #   public_id = document.pdf.file.public_id
      #   Cloudinary::Api.delete_resources([public_id], :type => :private)
      #   document.delete
      # end
      delivery.cancel!
      # if bus_to_delete.present?
      #   if bus_to_delete.factory_orders.last.present?
      #     # bus_to_delete.factory_orders.last.documents.each do |document|
      #     #   public_id = document.pdf.file.public_id
      #     #   Cloudinary::Api.delete_resources([public_id], :type => :private)
      #     #   document.delete
      #     end
      #     factory_order = line.bus.factory_orders.last
      #     factory_order.delete
      # end

      # if bus_to_cancel.present?
      #   bus_to_cancel.statut2 = "Annulé"
      #   bus_to_cancel.save
      # end
    end
  end

  def search_stock
    # doit retourner l'ensemble des véhicules qui ne sont pas lié à une commande client

    @buses = @q.result.where(statut1: ["indisponible","disponible"]).includes(:type) - Bus.ordered
  end

  def order_params
    params.require(:order).permit(
      :client,
      :numero_bon_de_commande,
      :date,
      :sales_advisor_id,
      :statut,
      :departement
    )
  end

  def bus_params
    params.require(:bus).permit(
      :description_id,
      :statut1,
      :statut2,
      lines_attributes: [
        :id,
        :couleur_ext_vehicule,
        :order_id,
        :order_book_id,
        :date_livraison_bdc,
        :mention_telematique,
        :mention_garantie,
        :_destroy
      ]
    )
  end
end

app/views/orders/_busencommande.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Bus liés à la commande</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Marque</th>
          <th>type</th>
          <th>Long. </th>
          <th>Places</th>
          <th>V.C.L</th>
          <th>Couleur Ext. Commandée</th>
           <th>Date Livraison bdc</th>
          <th>Garantie</th>
          <th>Telematique</th>
          <th>Status 2</th>
          <% if @order.pending?  %>
          <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @ordered_buses.each  do | bus| %>
        <tr>
          <td><%= bus.marque  %></td>
          <td><%= bus.type.name if bus.type.present?  %></td>
          <td><%= bus.longueur  %></td>
          <td><%= bus.nbr_places %></td>
          <td><%= bus.volo_coach_line %></td>

          <td><%= bus.lines.last[:couleur_ext_vehicule] if bus.lines.present? %></td>
          <td><%= bus.lines.last[:date_livraison_bdc] if bus.lines.present? %></td>
          <td><%= bus.lines.last[:mention_garantie] if bus.lines.present? %></td>
          <td><%= bus.lines.last[:mention_telematique] if bus.lines.present? %></td>
          <td><%= bus.statut2 %></td>
          <% if @order.pending?  %>
          <td>
            <%= link_to bus_path(bus[:id]), class: "btn btn-warning" do %>
            <i class="far fa-edit"></i><% end %>

             <%= link_to new_order_bus_line_trade_path(@order, bus[:id], @order.lines.where(bus_id: bus[:id]).take), class: "btn btn-primary" do %><i class="fas fa-bus"></i><% end %>

            <%= link_to new_order_bus_line_training_path(@order, bus[:id], @order.lines.where(bus_id: bus[:id]).take), class: "btn btn-primary" do %><i class="fas fa-graduation-cap"></i><% end %>

            <% if bus.lines.present? %>
            <%= link_to line_path(bus.lines.last), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} do %>
            <i class="fas fa-minus-circle"></i>
            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/_busenreprise.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Reprise</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Immatriculation</th>
          <th>Statut 2</th>
          <th>Prix de rachat</th>
          <th>Bus lié à la reprise</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @order.lines.each  do |line| %>
          <% line.trades.each do |trade| %>
            <tr>
              <td><%= trade.bus.immatriculation %></td>
              <td><%= trade.bus.statut2 %></td>
              <td><%= trade.prix_achat %></td>
              <td><%= line.bus.type.name  if line.bus.type.present? %></td>
            <td>
              <%= link_to bus_path(trade.bus), class: "btn btn-warning" do %>
              <i class="far fa-edit"></i>
              <% end %>
              <%= link_to trade_path(trade),method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} do %>
              <i class="fas fa-minus-circle"></i>
              <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/_formations_demandees.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Formations</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Lieu</th>
          <th>Formateur</th>
          <th>Bus lié à la formation</th>
          <th>action</th>
        </tr>
      </thead>
      <tbody>
        <% @order.lines.each  do |line| %>
          <% if line.training.present? %>
        <tr>
          <td><%= line.training.date  %></td>
          <td><%= line.training.lieu %></td>
          <td><%= line.training.formateur %></td>
          <td><%= line.bus.type.name if line.bus.type.present?%></td>
          <td>
            <%= link_to training_path(line.training), method: :delete,  class: "btn btn-danger", data: {confirm: "Are you sure?"} do %>
            <i class="fas fa-minus-circle"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/_list_bus.html.erb
     <div class="tab">
          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"></div>
            <!-- Table -->
            <table class="table">
              <thead>
                <tr>
                  <th>Description</th>
                  <th>Couleur Exterieure</th>
                  <th>Client</th>
                  <th>Status 1</th>
                  <th>Status 2</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <% @buses.each  do | bus| %>
                <tr>
                  <td><%= bus.description[:name] %></td>
                  <td><%= bus.lines.last[:couleur_ext_vehicule] if bus.lines.last.present? %></td>
                  <td><%= bus.orders.last[:client] if bus.orders.last.present?%></td>
                  <td><%= bus.status1 %></td>
                  <td><%= bus.status2 %></td>
                  <td><%= link_to new_order_line_path(@order, bus.id), class: "btn btn-warning" do %>
                    <i class="far fa-edit"></i>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

app/views/orders/_list_buses.html.erb
     <div class="tab">
          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">Liste des véhicules en stock correspondant à la recherche</div>
            <!-- Table -->
            <table class="table">
              <thead>
                <tr>
                  <th>Marque</th>
                  <th>type</th>
                  <th>Long. </th>
                  <th>Places</th>
                  <th>V.C.L</th>
                  <th>N° Chassis</th>
                  <th>Statut 1</th>
                  <th>Statut 2</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <% @buses.each  do | bus| %>
                <tr>
                  <td><%= bus.marque  %></td>
                  <td><%= bus.type.name if bus.type.present? %></td>
                  <td><%= bus.longueur  %></td>
                  <td><%= bus.nbr_places %></td>
                  <td><%= bus.volo_coach_line %></td>
                  <td><%= bus.numero_chassis %></td>
                  <td><%= bus.statut1 %></td>
                  <td><%= bus.statut2 %></td>
                  <td><%= link_to new_order_bus_line_path(@order, bus), class: "btn btn-warning" do %>
                    <i class="fas fa-cart-plus"></i>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div>
          <%= link_to new_order_bus_path(@order), class: "btn btn-primary" do %>Commander un bus à l'usine
          <% end %>
        </div>

app/views/orders/_list_orders.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents-->
    <div class="panel-heading">
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Client</th>
          <th>N° Bdc</th>
          <th>Vendeur</th>
          <th>Date</th>
          <th>Departement</th>
          <th>action</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= order.client %></td>
          <td><%= order.numero_bon_de_commande %></td>
          <td><%= order.sales_advisor[:name] %></td>
          <td><%= order.date %></td>
          <td><%= order.departement %></td>
          <td>
            <%= link_to order_path(order[:id]), class: "btn btn-primary" do %>
          <i class="far fa-eye"></i><% end %>
          <% if order.pending?  %>
            <%= link_to edit_order_path(order[:id]), class: "btn btn-warning" do %>
          <i class="far fa-edit"></i><% end %>

          <%= link_to bulk_update_path(order), class: "btn btn-danger", data: {confirm: "Are you sure?"} do %><i class="fas fa-minus-circle"></i><% end %>
          <% end %>
            </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/_list_used_buses.erb
<div class="tab">
          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"></div>
            <!-- Table -->
            <table class="table">
              <thead>
                <tr>
                  <th>Description</th>
                  <th>Immatriculation</th>
                  <th>Couleur Exterieure</th>
                  <th>Client</th>
                  <th>Status 1</th>
                  <th>Status 2</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <% @used_buses.each  do | bus| %>
                <tr>
                  <td><%= bus.description[:name] %></td>
                  <td><%= bus.immatriculation %> </td>
                  <td><%= bus.lines.last[:couleur_ext_vehicule] if bus.lines.last.present? %></td>
                  <td><%= bus.orders.last[:client] if bus.orders.last.present?%></td>
                  <td><%= bus.status1 %></td>
                  <td><%= bus.status2 %></td>
                  <td><%= link_to new_order_line_path(@order, bus.id), class: "btn btn-warning" do %>
                    <i class="far fa-edit"></i>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

app/views/orders/_no_bus.html.erb
<h5>Aucun bus en stock ne correspond à votre recherche</h5>
<%= link_to new_order_bus_path(@order), class: "btn btn-primary" do %>
                    Commander un bus à l'usine
                    <% end %>

app/views/orders/archive.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Commandes traitées", closed_orders_path, class: "tab-underlined  " %>
  </li>
  <li>
    <%= link_to "Commandes annulées", archive_orders_path, class: "tab-underlined active " %>
  </li>
</ul>
</div>
<div class="container">
<%= render 'list_orders'  %>
</div>

app/views/orders/closed.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Commandes traitées", closed_orders_path, class: "tab-underlined active " %>
  </li>
  <li>
    <%= link_to "Commandes annulées", archive_orders_path, class: "tab-underlined  " %>
  </li>
</ul>
</div>
<div class="container">
<%= render 'list_orders'  %>
</div>

app/views/orders/edit.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined active" %>
  </li>
  <li>
    <%= link_to "Commandes traitées", closed_orders_path, class: "tab-underlined  " %>
  </li>
  <li>
    <%= link_to "Commandes annulées", archive_orders_path, class: "tab-underlined  " %>
  </li>
</ul>
</div>
<div class="form-container">
<%= simple_form_for @order do |f| %>
  <%= f.input :client %>
  <%= f.input :numero_bon_de_commande %>
  <%= f.input :date, as: :date, html5: true  %>
  <%= f.association :sales_advisor%>
  <%= f.input :departement %>
  <button type="submit" class="btn btn-primary">
                  Creer cette commande</i>
<% end %>
</div>

app/views/orders/index.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined active " %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Commandes traitées", closed_orders_path, class: "tab-underlined " %>
  </li>
</ul>
</div>
<div class="container">
<%= render 'list_orders'  %>
</div>

app/views/orders/new.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined active" %>
  </li>
  <li>
    <%= link_to "Commandes traitées", closed_orders_path, class: "tab-underlined  " %>
  </li>
  <li>
    <%= link_to "Commandes annulées", archive_orders_path, class: "tab-underlined  " %>
  </li>
</ul>
</div>
<div class="form-container">
<%= simple_form_for @order do |f| %>
  <%= f.input :client %>
  <%= f.input :numero_bon_de_commande  %>
  <%= f.input :date, as: :date, html5: true, label: "date signature bon de commande"  %>
  <%= f.association :sales_advisor%>
  <%= f.input :departement %>
  <button type="submit" class="btn btn-primary">
                  Creer cette commande</i>
<% end %>
</div>

app/views/orders/show.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined #{'active' if @order.pending? }" %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Commandes traitées", closed_orders_path, class: "tab-underlined " %>
  </li>
  <li>
    <%= link_to "Commandes annulées", archive_orders_path, class: "tab-underlined #{'active' unless @order.pending? } " %>
  </li>
</ul>
</div>

<div class="container">
  <div class="tab">
    <div class="panel panel-default">
      <!-- Default panel contents-->
      <div class="panel-heading">Commande</div>
      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>Client</th>
            <th>Date BdC</th>
            <th>N°BdC</th>
            <th>Vendeur</th>
            <th>Departement</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @order.client %></td>
            <td><%= @order.date %></td>
            <td><%= @order.numero_bon_de_commande %></td>
            <td><%= @order.sales_advisor[:name] %></td>
            <td><%= @order.departement %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

<% if @order.pending?  %>
  <h6>Rechercher un bus en stock par sa description</h6>
  <p>Il est possible de commander plusieurs Bus sur la même commande en effectuant une nouvelle recherche</p>
    <%= search_form_for @q, url: order_path(@order), html: { method: :get } do |f| %>
      <%= f.search_field :type_name_cont %>
      <%= f.submit  %>
    <% end %>
<% end %>

<% if params[:q]!=nil && @buses.length>0  %>
<%= render 'list_buses' %>
<% elsif params[:q].present? && @buses.length==0 %>
<%= render 'no_bus' %>
<% end %>
<br>
<%= render 'busencommande'%>

<!-- affichage du bus concerné par la reprise -->
<%= render 'busenreprise' if @order.trades.present? %>

<% if @order_to_close && @order.statut == true %>
  <h5>Cloturer cette commande</h5>
    <%= simple_form_for @order do |f| %>
      <%= f.input :statut, :input_html => { value: close}, as: :hidden  %>
      <button type="submit" class="btn btn-primary" %>
      Cloturer cette commande</button>
      <% end %>
<% elsif @order_to_close && @order.statut == false %>
        <div class="status_bar">Cette commande est cloturée</div>
<% end %>

<!-- affichage des formations demandés -->
<%= render 'formations_demandees' if @order.trainings.present? %>

<br>
<%= link_to "retour à la liste des commandes en cours", orders_path %>
</div>