config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'orders/buses-bulk-update/:id' => 'orders#bulk_update', :as => 'bulk_update'
  post 'orders/buses-bulk-update-save/:id' => 'orders#bulk_update_save', :as => 'bulk_update_save'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ferries, only: [:index, :show, :edit, :update, :destroy]
  resources :buses do
    collection do
      get 'vn'
      get 'vo'
    end
    collection do
      get 'archive'
    end
    resources :ferries, only: [:create]
  end
  resources :orders do
    collection do
      get 'closed'
      get 'archive'
    end
    resources :buses do
      resources :lines, only: [:new, :create] do
        resources :trades, only: [:new, :create]
        resources :buses, only: [:new, :create]
        resources :trainings, only: [:new, :create]
      end
    end
  end

  resources :factory_orders, only: [:show, :edit, :update] do
    resources :partners
  end
  resources :documents, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :deliveries, only: [:index, :show, :edit, :update] do
    member do
      get 'close'
    end
    collection do
      get 'archive'
    end
  end
  resources :lines, only: [:edit, :update, :destroy]
  resources :works, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :trades, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'archive'
    end
    member do
      get 'close'
    end
  end
  resources :trainings, only: [:destroy]

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
  has_many :lines, dependent: :destroy
  accepts_nested_attributes_for :lines
  has_many :factory_orders, dependent: :destroy
  accepts_nested_attributes_for :factory_orders
  belongs_to :description, optional: true
  belongs_to :type, optional: true
  has_many :orders, through: :lines
  has_many :ferries, dependent: :destroy
  accepts_nested_attributes_for :ferries
  has_many :trades, dependent: :destroy
  has_many :partners, through: :factory_orders
  accepts_nested_attributes_for :partners

  enum statut1: { disponible: 0, indisponible: 1, facture_livre: 2, en_commande: 3 }

  scope :ordered, -> { includes(:lines, :orders).where(orders: {statut: "pending"} ) }
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :place, optional: true
  has_one :line, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :works
  accepts_nested_attributes_for :works,  reject_if: :all_blank, allow_destroy: true
  has_one :order, through: :line
  has_one_attached :attestation_amenagement
  has_one_attached :coc
  has_one_attached :cpi
  has_one_attached :cerfa_changement_titulaire
  has_one_attached :cerfa_cession
  has_one_attached :bulletion_de_livraison
  has_one_attached :cdoc
  has_one_attached :attestation_ead
  has_one_attached :attestation_limiteur_de_vitesse
  has_one_attached :photos_vehicule
  has_one_attached :facture
  has_one_attached :bon_de_commande
  has_one_attached :offre_configuration_avec_plan_implantation
  has_one_attached :information_peinture
  has_one_attached :plan_vosp
  has_one_attached :fiche_rcr
  has_one_attached :a_reception_envoi_papiers_originaux
  has_one_attached :justificatif_financement

  enum statut: { pending: 0, close: 1, cancel: 2 }
end

app/models/description.rb
class Description < ApplicationRecord
  has_many :buses
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :factory_order, optional: true
  belongs_to :delivery, optional: true
  belongs_to :trade, optional: true
  mount_uploader :pdf, PfdFileUploader
end

app/models/employee_partner.rb
class EmployeePartner < ApplicationRecord
  belongs_to :partner, optional: true
end

app/models/factory_order.rb
class FactoryOrder < ApplicationRecord
  belongs_to :bus, optional: true
  belongs_to :partner, optional: true
  has_many :documents, dependent: :destroy
  has_many :employee_partners, through: :partner
  has_one_attached :vcr
  has_one_attached :document_de_transport
  has_one_attached :delivery_note
  has_one_attached :vcr
  has_many_attached :photos_livraison

  enum statut: { pending: 0, close: 1, cancel: 2 }

end

app/models/ferry.rb
class Ferry < ApplicationRecord
  belongs_to :bus, optional: true
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order
  belongs_to :bus
  belongs_to :order_book, optional: true
  has_many :trades, dependent: :destroy
  has_one :training, dependent: :destroy
  belongs_to :delivery, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :sales_advisor
  validates :sales_advisor, presence: true
  has_many :lines, dependent: :delete_all
  has_many :buses, through: :lines
  has_many :trades, through: :lines, dependent: :destroy
  has_many :trainings, through: :lines, dependent: :destroy

  enum statut: { pending: 0, close: 1, archive: 2 }
end

app/models/order_book.rb
class OrderBook < ApplicationRecord
  has_many :lines
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :factory_orders
  has_many :employee_partners
  has_many :buses, through: :factory_orders
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :deliveries
end

app/models/sales_advisor.rb
class SalesAdvisor < ApplicationRecord
  has_many :orders
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :work, optional: true
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :line
  belongs_to :bus
  has_many :documents, dependent: :destroy
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :line
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :buses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :delivery, optional: true
  has_one_attached :devis
  has_one_attached :facture_travaux
end

app/controllers/ferries_controller.rb
class FerriesController < ApplicationController
  def index
    @ferries = Ferry.all
  end

  # def new
  #   @ferry = Ferry.new
  #   @bus = Bus.find(params[:bus_id])
  # end

  def create
    @ferry = Ferry.new(ferry_params)
    @bus = Bus.find(params[:bus_id])
    @order = @bus.orders.pending.take
    @line = @order.lines.where(bus_id: @bus.id).take if @order.present?
    # @delivery = Delivery.find(@line.delivery_id) if @order.present?
    @ferry.bus = @bus
    if @ferry.save
      respond_to do |format|
        format.html { redirect_to bus_path(@bus) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'buses/show' }
        format.js
      end
    end
  end

  def edit
    @ferry = Ferry.find(params[:id])
  end

  def update
    @ferry = Ferry.find(params[:id])
    @bus = Bus.find(params[:bus_id])
    @ferry.update(ferry_params)
    # @delivery = Delivery.find(session[:delivery_id])
    redirect_to bus_path(@delivery)
  end

  def destroy
    @ferry = Ferry.find(params[:id])
    @ferry.delete
    redirect_to ferries_path
  end

  def show
    @ferry = Ferry.find(params[:id])
  end

  private

  def ferry_params
    params.require(:ferry).permit(
      :depart,
      :arrivee,
      :date_convoyage,
      :site,
      :note,
      :numero_bdc,
      :sens
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ferries/_list_ferries.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"></div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Marque</th>
            <th>type</th>
            <th>Long. </th>
            <th>Places</th>
            <th>V.C.L</th>
            <th>Couleur</th>
            <th>N° de Chassis</th>
            <th>N° immat</th>
            <th>Départ</th>
            <th>Arrivée</th>
            <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @ferries.each  do | ferry| %>
        <tr>
            <td><%= ferry.bus.marque %></td>
            <td><%= ferry.bus.type.name if ferry.bus.type.present?%></td>
            <td><%= ferry.bus.longueur %></td>
            <td><%= ferry.bus.nbr_places %></td>
            <td><%= ferry.bus.volo_coach_line %></td>
            <td><%= ferry.bus.couleur %></td>
            <td> <%= ferry.bus.numero_chassis %></td>
            <td> <%= ferry.bus.immatriculation %></td>
            <td><%= ferry.depart %></td>
            <td><%= ferry.arrivee %></td>
          <td>
            <%= link_to edit_ferry_path(ferry[:id]), class: "btn btn-warning" do %><i class="far fa-edit"></i><% end %>
            <%= link_to ferry_path(ferry[:id]), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} do %><i class="fas fa-minus-circle"></i><% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/ferries/_new_ferry.html.erb
<%= simple_form_for([ bus, ferry ], remote: true) do |f| %>
  <%= f.input :date_convoyage, as: :date, html5: true %>
 <div class="row">
      <div class="col-sm-6 col-xs-12">
  <%= f.input :depart, label: "Lieu de départ" %>
      </div>
      <div class="col-sm-6 col-xs-12">
  <%= f.input :arrivee, label: "lieu d'arrivée" %>
      </div>
  </div>
  <%= f.input :note, as: :text, label: "Note (nom du convoyeur)" %>
  <%= f.submit "Convoyer", class: "btn btn-primary" %>
<% end %>

app/views/ferries/_show.html.erb
  <td><%= ferry.date_convoyage %></td>
  <td><%= ferry.depart %></td>
  <td><%= ferry.arrivee %></td>
  <%= simple_form_for ferry do |f| %>
  <td><%= f.input :site, label: false%></td>
  <td><%= f.input :numero_bdc, label: false %></td>
  <td><button type="submit" class="btn btn-primary">
    <i class="far fa-save"></i>
  </button><% end %></td>

app/views/ferries/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_ferry');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const ferries = document.getElementById('ferries');
  ferries.insertAdjacentHTML('beforebegin', reviewHTML);
}

<% if @ferry.errors.any? %>
  refreshForm('<%= j render "ferries/new_ferry", bus: @bus, ferry: @ferry %>');
<% else %>
  addReview('<%= j render "ferries/show", ferry: @ferry %>');
  refreshForm('<%= j render "ferries/new_ferry", bus: @bus, ferry: Ferry.new %>');
<% end %>

app/views/ferries/edit.html.erb
<div class="container">
<%= simple_form_for [@bus, @ferry] do |f| %>
  <%= f.input :date_convoyage, as: :date, html5: true %>
  <%= f.input :depart %>
  <%= f.input :arrivee %>
  <%= f.input :site %>
  <%= f.input :numero_bdc %>
  <%= f.input :note, as: :text %>
  <%= f.submit "Mettre à jour", class: "btn btn-primary" %>
<% end %>
</div>

app/views/ferries/index.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Convoyages en cours", ferries_path, class: "tab-underlined active " %>
  </li>
</ul>
</div>
  <div class="container">
      <%= render 'list_ferries'  %>
  </div>

app/views/ferries/new.html.erb
<div class = "wrapper">
  <ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Preparation Livraisons", deliveries_path, class: "tab-underlined active " %>
  </li>
  <li>
    <%= link_to "Archives", archive_deliveries_path, class: "tab-underlined " %>
  </li>
</ul>
</div>

<div class="form-container">
<%= simple_form_for [@bus, @ferry] do |f| %>
  <%= f.input :date_convoyage, as: :date, html5: true %>
 <div class="row">
      <div class="col-sm-6 col-xs-12">
  <%= f.input :depart, label: "Lieu de départ" %>
      </div>
      <div class="col-sm-6 col-xs-12">
  <%= f.input :arrivee, label: "lieu d'arrivée" %>
      </div>
  </div>
  <%= f.input :note, as: :text, label: "Note (nom du convoyeur)" %>
  <%= f.submit "Convoyer", class: "btn btn-primary" %>
<% end %>
</div>