config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'orders/buses-bulk-update/:id' => 'orders#bulk_update', :as => 'bulk_update'
  post 'orders/buses-bulk-update-save/:id' => 'orders#bulk_update_save', :as => 'bulk_update_save'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ferries, only: [:index, :show, :edit, :update, :destroy]
  resources :buses do
    collection do
      get 'vn'
      get 'vo'
    end
    collection do
      get 'archive'
    end
    resources :ferries, only: [:create]
  end
  resources :orders do
    collection do
      get 'closed'
      get 'archive'
    end
    resources :buses do
      resources :lines, only: [:new, :create] do
        resources :trades, only: [:new, :create]
        resources :buses, only: [:new, :create]
        resources :trainings, only: [:new, :create]
      end
    end
  end

  resources :factory_orders, only: [:show, :edit, :update] do
    resources :partners
  end
  resources :documents, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :deliveries, only: [:index, :show, :edit, :update] do
    member do
      get 'close'
    end
    collection do
      get 'archive'
    end
  end
  resources :lines, only: [:edit, :update, :destroy]
  resources :works, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :trades, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'archive'
    end
    member do
      get 'close'
    end
  end
  resources :trainings, only: [:destroy]

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  def index
    session[:order_id] = nil
    @descriptions = Description.all
    @types = Type.all
    @orders = Order.all
    @buses = Bus.where.not(statut1: :facture_livre)
  end

  def vn
    session[:order_id] = nil
    @descriptions = Description.all
    @types = Type.all
    @orders = Order.all
    @buses = Bus.where.not(statut1: :facture_livre).where.not("statut2 = 'Stock VO'")
  end

  def vo
    session[:order_id] = nil
    @descriptions = Description.all
    @types = Type.all
    @orders = Order.all
    @buses = Bus.where("statut2 = 'Stock VO'")
  end

  def show
    session[:delivery_id] = nil
    session[:order_id] = nil
    session[:trade_id] = nil
    set_documents
    @bus = Bus.find(params[:id])
    session[:bus_id] = @bus.id

    if @bus.factory_orders.pending.last.present?
      @factory_order = @bus.factory_orders.pending.last
      # @partners = Partner.all
    else
      @factory_order = @bus.factory_orders.build
      # @partners = Partner.all
    end

    # @bus.ferries.build
    @order = @bus.orders.pending.take
    @line = @order.lines.where(bus_id: @bus.id).take if @order.present?
    @delivery = Delivery.find(@line.delivery_id) if @order.present?
    @active_trade = @bus.trades.where("status = true").take
    @ferry = Ferry.new
  end

  def new
    @bus = Bus.new
    @descriptions = Description.all
    @types = Type.all
    @order = Order.find(params[:order_id]) if params[:order_id].present?
    @ordered_bus = Bus.find(params[:bus_id]) if params[:bus_id].present?
    @line = Line.find(params[:line_id]) if params[:line_id].present?
    #@buses = Bus.all
    #@orders = Order.all
  end

  def create
    @bus = Bus.new(bus_params)
    @bus.marque = "Volvo" if !bus_params[:marque].present?
    @order = Order.find(params[:order_id]) if params[:order_id].present?
    @ordered_bus = Bus.find(params[:bus_id]) if params[:bus_id].present?
    @line = Line.find(params[:line_id]) if params[:line_id].present?
    if @order.present? && !@ordered_bus.present?
      @bus.statut2 = "A commander"  # statut2 force à "a commander" car bus indisponible en stock
      if @bus.save
        redirect_to new_order_bus_line_path(@order, @bus.id)
      else
        render :new
      end
    elsif @order.present? && @ordered_bus.present?
      @bus.facture_livre! # statut1 forcé à "client " car le bus crée est un VO à reprendre et appartient toujours à son client

      if @bus.save
        redirect_to new_order_bus_line_trade_path(@order, @ordered_bus, @line, @bus.id)
      else
        render :new
      end
    elsif @bus.save
      redirect_to vn_buses_path(@bus)
    else
      render :new
    end
  end

  def edit
    @bus = bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])
    @bus.update(bus_params)
    redirect_to bus_path(@bus)
  end

  def destroy
    @bus = Bus.find(params[:id])
    id = @bus.orders.last.id
    @bus.destroy
    redirect_to order_path(id)
  end

  def archive
    @buses = @buses = Bus.facture_livre
  end

  private

  def set_documents
    @documents_factory_delivery = [
      "VCR",
      "Document de transport",
      "Delivery Note",
      "Photo livraison usine"
    ]
  end

  def bus_params
    params.require(:bus).permit(
      :statut1,
      :statut2,
      :description_id,
      :type_id,
      :ch_cb,
      :sept_neuf,
      :numero_chassis,
      :reference_usine,
      :designation_configuration,
      :bo_number,
      :date_debut_garantie,
      :kilometrage,
      :date_kilometrage,
      :immatriculation,
      :option_contremarque,
      :option_commercial,
      :date_option,
      :prix_mini,
      :version,
      :implantation,
      :longueur,
      :nbr_places,
      :couleur,
      :volo_coach_line,
      :note,
      :reference,
      :marque,
      factory_orders_attributes: [
        :id,
        :envoiOF,
        :date_limit_modif_config,
        :reception_oc,
        :dispo_fr,
        :CDD,
        :_destroy,
        :lieu_depart_usine,
        :date_depart_usine,
        :lieu_arrivee_partenaire_volvo,
        :date_arrivee_partenaire_volvo,
        :partenaire_prevenu,
        :statut
        ],
      ferries_attributes: [
        :id,
        :date_convoyage,
        :depart,
        :arrivee,
        :sens,
        :site,
        :numero_bdc,
        :note
        ]
     )
  end
end

app/views/buses/_emplacement.html.erb
      <div class="tab">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading"></div>
          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Départ</th>
                <th>Arrivée</th>
                <th>Sites prevenus</th>
                <th>N°bdc pour le convoyage crée</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr id="ferries">
                <% @bus.ferries.each  do | ferry| %>
                <%= render 'ferries/show', ferry: ferry %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <%= render 'ferries/new_ferry', bus: @bus, ferry: @ferry %>

app/views/buses/_identification_usine.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents
    <div class="panel-heading">Bus en stock</div>-->
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>BO N°</th>
          <th>N°Chassis</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= simple_form_for @bus do |f| %>
        <tr>
          <td><%= f.input :bo_number, label: false %></td>
          <td><%= f.input :numero_chassis, label: false %></td>
          <td><button type="submit" class="btn btn-primary">
            <i class="far fa-save"></i>
            </button></td>
        </tr>
        </tbody>
      </table>

            <% end %>
    </div>
  </div>

app/views/buses/_immatriculation.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents
    <div class="panel-heading">Bus en stock</div>-->
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Kilometrage</th>
          <th>Date du relevé du Kilometrage</th>
          <th>Numero Immat.</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= simple_form_for @bus do |f| %>
        <tr>
          <td><%= f.input :date_debut_garantie, as: :date, html5: true, label: false %></td>
          <td><%= f.input :kilometrage, label: false %></td>
          <td><%= f.input :date_kilometrage, as: :date, html5: true, label: false %></td>
          <td><%= f.input :immatriculation, label: false %></td>
          <td><button type="submit" class="btn btn-primary">
    <i class="far fa-save"></i>
    </button></td>
        </tr>
      </tbody>
    </table>

    <% end %>
  </div>
</div>

app/views/buses/_livraison_usine.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"></div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Documents</th>
          <th>Download</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><% if @factory_order.vcr.attached? %>
            <%= link_to pdfjs.full_path(file:"#{url_for(@factory_order.vcr)}"), target: "_blank" do %>
            <%= @factory_order.vcr.name %>
            <% end %>
            <%= link_to rails_blob_path(@factory_order.vcr, disposition: 'attachment') do%>
            <i class="far fa-save"></i>
            <% end %>
            <% else %>
            <%= @factory_order.vcr.name %>
            <% end %>
          </td>
          <td><%= simple_form_for @factory_order do |form| %>
            <%= form.file_field :vcr %>
            <button type="submit" class="btn btn-primary">
            <i class="far fa-save"></i>
            </button>
            <% end %>
          </td>
        </tr>

        <tr>
          <td><% if @factory_order.document_de_transport.attached? %>
            <%= link_to pdfjs.full_path(file:"#{url_for(@factory_order.document_de_transport)}"), target: "_blank" do %>
            <%= @factory_order.document_de_transport.name %>
            <% end %>
            <%= link_to rails_blob_path(@factory_order.document_de_transport, disposition: 'attachment') do%>
            <i class="far fa-save"></i>
            <% end %>
            <% else %>
            <%= @factory_order.document_de_transport.name %>
            <% end %>
          </td>
          <td><%= simple_form_for @factory_order do |form| %>
            <%= form.file_field :document_de_transport %>
            <button type="submit" class="btn btn-primary">
            <i class="far fa-save"></i>
            </button>
            <% end %>
          </td>
        </tr>

        <tr>
          <td><% if @factory_order.photos_livraison.attached? %>
            <%= link_to pdfjs.full_path(file:"#{url_for(@delivery.photos_livraison)}"), target: "_blank" do %>
            <%= @factory_order.photos_livraison.name %>
            <% end %>
            <%= link_to rails_blob_path(@factory_order.photos_livraison, disposition: 'attachment') do%>
            <i class="far fa-save"></i>
            <% end %>
            <% else %>
            <%= @factory_order.photos_livraison.name %>
            <% end %>
          </td>
          <td><%= simple_form_for @factory_order do |form| %>
            <%= form.file_field :photos_livraison, multiple: true %>
            <button type="submit" class="btn btn-primary">
            <i class="far fa-save"></i>
            </button>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents
    <div class="panel-heading">Bus en stock</div>-->
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Photo niveau d’essence à l’arrivée</th>
          <th>Avarie Usine</th>
          <th>Détails (Transporteur / Process avarie)</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
         <%= simple_form_for @factory_order do |f| %>
        <tr>
          <td><%= f.input :photos_envoyees_usine, label: false %></td>
          <td><%= f.input :avarie, label: false %></td>
          <td><%= f.input :details_avarie, label: false %></td>
          <td>
            <button type="submit" class="btn btn-primary">
            <i class="far fa-save"></i>
            </button>
            <% end %></td>
        </tr>
      </tbody>
    </table>

  </div>
</div>

app/views/buses/_maj_commande_usine.html.erb
<%= simple_form_for @factory_order do |f| %>
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents
    <div class="panel-heading">Bus en stock</div>-->
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Envoi OF</th>
          <th>date limite modif. Config.</th>
          <th>reception OC</th>
          <th>Dispo FR demandée</th>
          <th>CDD</th>
        </tr>
      </thead>
      <tbody>

        <tr>
          <td><%= f.input :envoiOF, label: false %></td>
          <td><%= f.input :date_limit_modif_config, as: :date, html5: true, label: false %></td>
          <td><%= f.input:reception_oc, label: false %></td>
          <td><%= f.input :dispo_fr, as: :boolean, label: false %></td>
          <td><%= f.input :CDD, as: :date, html5: true, label: false %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents
    <div class="panel-heading">Bus en stock</div>-->
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Lieu départ Usine</th>
          <th>Date Départ Usine</th>
          <th>lieu Arrivée chez Partenaire Volvo</th>
          <th>Date Arrivée chez partenaire Volvo</th>
          <th>Email Partenaire Volvo</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.input :lieu_depart_usine, label: false %></td>
          <td><%= f.input :date_depart_usine, as: :date, html5: true, label: false %></td>
          <td><%= f.input :lieu_arrivee_partenaire_volvo, label: false %></td>
          <td><%= f.input :date_arrivee_partenaire_volvo, as: :date, html5: true, label: false %></td>
           <%# f.simple_fields_for :partners do |part| %>
             <%# part.simple_fields_for :employee_partners do |e| %>
            <td><%# e.input :email, collection: EmployeePartner.all.map {|emp| emp.email}, label: false  %></td>
            <%#end%>
          <%#end%>
        </tr>
      </tbody>
    </table>
    <button type="submit" class="btn btn-primary">
            <i class="far fa-save"></i>
            </button>
            <% end %>
            <%= simple_form_for @factory_order do |f| %>
      <%= f.hidden_field :statut, { value: 'cancel' }  %>
     <%= f.submit 'supprimer cette commande usine' %>
     <% end %>
  </div>
</div>

app/views/buses/_nouvelle_commande_usine.html.erb
<%= simple_form_for @bus do |f| %>
<%= f.simple_fields_for :factory_orders do |factory_orders_form| %>
      <%= factory_orders_form.hidden_field :statut, { value: 'pending' }  %>
    <button type="submit" class="btn btn-primary">Commander ce véhicule à l'usine</i></button><% end %>
    <% end %>

app/views/buses/_offre.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents
    <div class="panel-heading">Bus en stock</div>-->
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Option Contremarque</th>
          <th>Option Commercial</th>
          <th>Date Option</th>
          <th>Prix mini(renta 12%, sauf 8600 6%)</th>
          <th>Version</th>
          <th>Implantation</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= simple_form_for @bus do |f| %>
        <tr>
          <td><%= f.input :option_contremarque, label: false %></td>
          <td><%= f.input :option_commercial, label: false %></td>
          <td><%= f.input :date_option, as: :date, html5: true, label: false %></td>
          <td><%= f.input :prix_mini, label: false %></td>
          <td><%= f.input :version, label: false %></td>
          <td><%= f.input :implantation, label: false %></td>
          <td><button type="submit" class="btn btn-primary">
    <i class="far fa-save"></i>
    </button></td>
        </tr>
      </tbody>
    </table>

    <% end %>
  </div>
</div>

app/views/buses/_order.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents-->
    <div class="panel-heading">
    </div>
    <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>Client</th>
            <th>N° Bdc</th>
            <th>Vendeur</th>
            <th>Date de commande</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @order.client if @order.present? %></td>
            <td><%= @order.numero_bon_de_commande if @order.present? %></td>
            </td>
            <td><%= @order.sales_advisor.name if @order.sales_advisor.present? %></td>
            <td><%= @order.date if @order.date.present? %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents-->
    <div class="panel-heading">
    </div>
    <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>Order Book</th>
            <th>Date livraison bdc</th>
            <th>Couleur ext vehicule</th>
            <th>Mention garantie</th>
            <th>Mention telematique</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @line.order_book.name if @line.order_book.present? %></td>
            <td><%= @line.date_livraison_bdc if @order.present? %></td>
            <td><%= @line.couleur_ext_vehicule if @order.present? %></td>
            <td><%= @line.mention_garantie if @order.present? %></td>
            <td><%= @line.mention_telematique if @order.present? %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

app/views/buses/_releve_kilometrage.html.erb
<div class="tab">
  <div class="panel panel-default">
    <!-- Default panel contents
    <div class="panel-heading">Bus en stock</div>-->
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>kilometrage</th>
          <th>Date de relevé</th>
          <th>Action</th>

        </tr>
      </thead>
      <tbody>
        <%= simple_form_for @bus do |f| %>
        <tr>
          <td><%= f.input :kilometrage, label: false %></td>
          <td><%= f.input :date_kilometrage, as: :date,  html5: true, label: false %></td>
          <td><button type="submit" class="btn btn-primary">
            <i class="far fa-save"></i>
            </button></td>
        </tr>
        </tbody>
      </table>

            <% end %>
    </div>
  </div>

app/views/buses/index.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Véhicule en stock", buses_path, class: "tab-underlined active " %>
  </li>
  <li>
    <%= link_to "Ajouter un véhicule en stock", new_bus_path(), class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Véhicule chez le client", archive_buses_path, class: "tab-underlined " %>
  </li>
</ul>
</div>
<div class="container">
  <%= render 'list_buses'  %>
</div>

app/views/buses/new.html.erb
<% if !@order.present? %>
<div class = "wrapper">
  <ul class="list-inline tabs-underlined">
    <li>
      <%= link_to "Ajouter un véhicule en stock", new_bus_path(), class: "tab-underlined active" %>
    </li>
    <li>
      <%= link_to "VN en stock", vn_buses_path, class: "tab-underlined" %>
    </li>
    <li>
      <%= link_to "VO en stock", vo_buses_path, class: "tab-underlined" %>
    </li>
    <li>
      <%= link_to "Véhicule chez le client", archive_buses_path, class: "tab-underlined " %>
    </li>
  </ul>
</div>

<div class="form-container">
  <%= simple_form_for @bus do |f| %>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :statut1, collection: Bus.statut1s.map { |key, value| [key.humanize, key] } %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :statut2, collection: [ 'A commander',
      'Config usine à valider',
      'En commande',
      'Annulé',
      'En Stock SE35',
      'Stock VO',
      'En stock VTFL',
      'Démo SE35',
      'Démo FR05',
      'Facturé VN',
      'Facturé VTFL',
      'VO à rentrer',
      'Facturé VO',
      'Facturé VO (ex Demo)'] %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :type_id, collection: @types%>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :longueur %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :nbr_places %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :volo_coach_line %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :couleur %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :note %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :reference %>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Creer ce véhicule</button>
  <% end %>
</div>
  <% end %>
  <% if @order.present? && !@ordered_bus.present?  %>
  <div class = "wrapper">
  <ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined " %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined active " %>
  </li>
  <li>
    <%= link_to "Commandes traitées", archive_orders_path, class: "tab-underlined " %>
  </li>
</ul>
</div>
  <div class="form-container">
    <%= simple_form_for [@order,@bus] do |f| %>
    <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :type_id, collection: @types%>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :longueur %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :nbr_places %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :volo_coach_line %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :couleur %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :note %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :reference %>
    </div>
  </div>
    <button type="submit" class="btn btn-primary">Creer ce véhicule</button>
    <% end %>
    </div>
    <% end %>

    <% if @ordered_bus.present? %>
    <div class = "wrapper">
    <ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Commandes en cours", orders_path, class: "tab-underlined" %>
  </li>
  <li>
    <%= link_to "Ajouter une commande", new_order_path, class: "tab-underlined active" %>
  </li>
  <li>
    <%= link_to "Commandes traitées", archive_orders_path, class: "tab-underlined " %>
  </li>
</ul>
</div>
    <div class="form-container">
      <h5><strong>Reprendre ce véhicule au  client : <%=@order.client %></strong></h5>
      <%= simple_form_for [@order,@ordered_bus,@line,@bus] do |f| %>
      <br>
      <%= f.input :marque, label: 'Préciser la Marque si différent de Volvo'%>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :immatriculation%>
      </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :numero_chassis%>
     </div>
    </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :type_id, collection: @types%>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :longueur %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :nbr_places %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :volo_coach_line %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :couleur %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <%= f.input :note %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
      <%= f.input :reference %>
    </div>
  </div>
      <button type="submit" class="btn btn-primary">Creer ce véhicule</button>
      <% end %>
      <% end %>
    </div>

app/views/buses/show.html.erb
<div class="main-container">
  <div class="navigation" id="sidebar">
    <ul>
      <br>
      <li><h5>Informations Véhicule</h5></a></li>
      <li><a href="#section-1">Commande Client</a></li>
      <li><a href="#section-2">Informations Véhicule</a></li>
      <li><a href="#section-3">Indentification Usine</a></li>
      <li><a href="#section-4">Commande Usine</a></li>
      <li><a href="#section-5">Livraison Usine</a></li>
      <li><a href="#section-6">Relevé Kilometrage</a></li>
      <li><a href="#section-7">Immatriculation</a></li>
      <li><a href="#section-13">Convoyage</a></li>
      <% if @delivery.present? %>
      <%= link_to "Informations Livraison", delivery_path(@delivery)%>
      <% end %>
      <% if @active_trade %>
      <%= link_to "VO à rentrer", trade_path(@active_trade)%>
      <% end %>
    </ul>
  </div>
  <div>
    <div class="add-padding-left" id="section-1">
      <h5>Informations Véhicule</h5>
      <%= render "bus_resume" %>
      <%= render "./buses/information_vehicule" %>
    </div>
    <div class="add-padding-left" id="section-2">
      <h5>Commande Client</h5>
      <% if @order.present?  %>
      <%= render "order" %>
      <% else %>
      <p>Pas de commande pour ce véhicule</p>
      <% end %>
    </div>
    <div class="add-padding-left" id="section-3">
      <h5>Indentification Usine</h5>
      <%= render "identification_usine" %>
    </div>
    <div class="add-padding-left" id="section-4">
      <h5>Commande Usine</h5>
      <%= render "nouvelle_commande_usine" if !@bus.factory_orders.last.id.present? %>
      <%= render "maj_commande_usine" if @bus.factory_orders.last.id.present?  %>
    </div>
    <div class="add-padding-left" id="section-5">
      <h5>Livraison Usine Chez le Partenaire </h5>
      <%= render "livraison_usine" if @bus.factory_orders.last.id.present?%>
    </div>
    <div class="add-padding-left" id="section-6">
      <h5>Relevé Kilométrage </h5>
      <%= render "releve_kilometrage"%>
    </div>
    <div class="add-padding-left" id="section-7">
      <h5>Immatriculation</h5>
      <%= render "immatriculation" %>
    </div>
    <div class="add-padding-left" id="section-7">
      <h5>Convoyage</h5>
      <%= render "emplacement" %>
    </div>
  </div>
</div>

app/views/buses/vn.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Ajouter un véhicule en stock", new_bus_path(), class: "tab-underlined" %>
  </li>
    <li>
    <%= link_to "VN en stock", vn_buses_path, class: "tab-underlined active " %>
  </li>
      <li>
    <%= link_to "VO en stock", vo_buses_path, class: "tab-underlined " %>
  </li>
  <li>
    <%= link_to "Véhicule chez le client", archive_buses_path, class: "tab-underlined " %>
  </li>
</ul>
</div>
<div class="container">
  <%= render 'list_buses'  %>
</div>

app/views/buses/vo.html.erb
<div class = "wrapper">
<ul class="list-inline tabs-underlined">
  <li>
    <%= link_to "Ajouter un véhicule en stock", new_bus_path(), class: "tab-underlined" %>
  </li>
    <li>
    <%= link_to "VN en stock", vn_buses_path, class: "tab-underlined " %>
  </li>
      <li>
    <%= link_to "VO en stock", vo_buses_path, class: "tab-underlined active " %>
  </li>
  <li>
    <%= link_to "Véhicule chez le client", archive_buses_path, class: "tab-underlined " %>
  </li>
</ul>
</div>
<div class="container">
  <%= render 'list_buses'  %>
</div>